export const GET_POKEMONS_FETCHING = "GET_POKEMONS_FETCHING";
export const GET_POKEMONS_FETCH = "GET_POKEMONS_FETCH";
export const GET_POKEMONS_FETCH_ERROR = "GET_POKEMONS_FETCH_ERROR";

export const GET_POKEMONS_BY_ID_FETCHING = "GET_POKEMONS_BY_ID_FETCHING";
export const GET_POKEMONS_BY_ID_FETCH = "GET_POKEMONS_BY_ID_FETCH";
export const GET_POKEMONS_BY_ID_FETCH_ERROR = "GET_POKEMONS_BY_ID_FETCH_ERROR";

export const SAVE_POS = "SAVE_POS"